export const ERROR_CODES = {
  WORKER_UNAUTHORIZED: "E_WORKER_UNAUTHORIZED",
  WORKER_REPLAY_REJECTED: "E_WORKER_REPLAY_REJECTED",
  WORKER_TIMESTAMP_INVALID: "E_WORKER_TIMESTAMP_INVALID",
  WORKER_LOCK_BUSY: "E_WORKER_LOCK_BUSY",
  QUEUE_ITEM_NOT_FOUND: "E_QUEUE_ITEM_NOT_FOUND",
  QUEUE_PROCESSING_FAILED: "E_QUEUE_PROCESSING_FAILED",
  RUNNER_FORBIDDEN_SOURCE: "E_RUNNER_FORBIDDEN_SOURCE",
  RUNNER_COMPILE_FAILED: "E_RUNNER_COMPILE_FAILED",
  RUNNER_EXEC_TIMEOUT: "E_RUNNER_EXEC_TIMEOUT",
  RUNNER_OUTPUT_LIMIT: "E_RUNNER_OUTPUT_LIMIT",
  RUNNER_RUNTIME_FAILED: "E_RUNNER_RUNTIME_FAILED",
  RUNNER_ISOLATION_UNAVAILABLE: "E_RUNNER_ISOLATION_UNAVAILABLE",
  RUNNER_ISOLATION_FAILED: "E_RUNNER_ISOLATION_FAILED",
} as const;

export type ErrorCode = (typeof ERROR_CODES)[keyof typeof ERROR_CODES];
