import { Problem } from "./types";

export const problemCatalog: Problem[] = [
  {
    id: "two-sum",
    title: "두 수의 합",
    difficulty: "Easy",
    tags: ["implementation", "hash-table"],
    summary: "두 수의 합이 target이 되는 인덱스 쌍을 찾으세요.",
    statement:
      "정수 배열 nums와 정수 target이 주어집니다. nums[i] + nums[j] = target을 만족하는 서로 다른 두 인덱스 i, j를 출력하세요. 정답은 항상 하나라고 가정합니다.",
    sampleInput: "4\n2 7 11 15\n9",
    sampleOutput: "0 1",
    starterCode: `#include <bits/stdc++.h>\nusing namespace std;\n\nint main() {\n  ios::sync_with_stdio(false);\n  cin.tie(nullptr);\n\n  int n, target;\n  cin >> n;\n  vector<int> a(n);\n  for (int i = 0; i < n; i++) cin >> a[i];\n  cin >> target;\n\n  // TODO\n  return 0;\n}\n`,
    sampleTests: [{ input: "4\n2 7 11 15\n9\n", output: "0 1\n" }],
    conceptGuide: {
      coreConcepts: ["해시맵으로 값 -> 인덱스를 저장", "현재 값의 보수(target-x) 존재 여부 확인"],
      approachSteps: ["배열을 왼쪽부터 순회", "보수가 있으면 즉시 출력", "없으면 현재 값을 해시맵에 추가"],
      pitfalls: ["같은 원소를 두 번 쓰지 않도록 순서 주의", "중복 값 처리 시 마지막 인덱스 덮어쓰기 주의"],
      complexity: { time: "O(N)", space: "O(N)" },
    },
  },
  {
    id: "valid-parentheses",
    title: "올바른 괄호 문자열",
    difficulty: "Easy",
    tags: ["stack", "string"],
    summary: "괄호 문자열이 올바르게 짝지어졌는지 판별합니다.",
    statement: "문자열 s가 주어집니다. (), {}, [] 세 종류 괄호가 모두 올바르게 열리고 닫히는지 출력하세요.",
    sampleInput: "()[]{}",
    sampleOutput: "true",
    starterCode: `#include <bits/stdc++.h>\nusing namespace std;\n\nint main() {\n  string s;\n  cin >> s;\n\n  // TODO\n  cout << "true\\n";\n  return 0;\n}\n`,
    sampleTests: [{ input: "()[]{}\n", output: "true\n" }],
    conceptGuide: {
      coreConcepts: ["스택에 여는 괄호를 저장", "닫는 괄호에서 top과 짝 확인"],
      approachSteps: ["문자를 순회", "여는 괄호 push", "닫는 괄호면 top 검사 후 pop", "끝났을 때 스택이 비면 true"],
      pitfalls: ["스택이 빈 상태에서 pop 시도", "괄호 종류 매핑 실수"],
      complexity: { time: "O(N)", space: "O(N)" },
    },
  },
  {
    id: "longest-increasing-subsequence",
    title: "가장 긴 증가 부분수열",
    difficulty: "Medium",
    tags: ["dp", "binary-search"],
    summary: "가장 긴 엄격 증가 부분수열의 길이를 구합니다.",
    statement: "정수 배열이 주어질 때 LIS(가장 긴 증가 부분수열)의 길이를 출력하세요.",
    sampleInput: "8\n10 9 2 5 3 7 101 18",
    sampleOutput: "4",
    starterCode: `#include <bits/stdc++.h>\nusing namespace std;\n\nint main() {\n  int n;\n  cin >> n;\n  vector<int> a(n);\n  for (int i = 0; i < n; i++) cin >> a[i];\n\n  // TODO\n  return 0;\n}\n`,
    sampleTests: [{ input: "8\n10 9 2 5 3 7 101 18\n", output: "4\n" }],
    conceptGuide: {
      coreConcepts: ["patience sorting 아이디어", "lower_bound로 길이별 최소 끝값 유지"],
      approachSteps: ["배열 순회", "현재 값이 들어갈 위치를 이분탐색", "끝에 붙이거나 교체", "벡터 길이가 정답"],
      pitfalls: ["upper_bound와 혼동하면 strict 증가 조건 깨짐"],
      complexity: { time: "O(N log N)", space: "O(N)" },
    },
  },
  {
    id: "prefix-sum-range",
    title: "구간 합 질의",
    difficulty: "Easy",
    tags: ["implementation", "prefix-sum"],
    summary: "여러 구간 [l, r]의 합을 빠르게 구하세요.",
    statement: "길이 N 배열과 Q개의 질의가 주어집니다. 각 질의 l r에 대해 구간 합을 출력하세요(1-indexed).",
    sampleInput: "5 3\n1 2 3 4 5\n1 3\n2 5\n4 4",
    sampleOutput: "6\n14\n4",
    starterCode: `#include <bits/stdc++.h>\nusing namespace std;\n\nint main(){\n  ios::sync_with_stdio(false);\n  cin.tie(nullptr);\n  int n,q; cin>>n>>q;\n  vector<long long>a(n+1), ps(n+1);\n  for(int i=1;i<=n;i++) cin>>a[i];\n  // TODO\n  return 0;\n}\n`,
    sampleTests: [{ input: "5 1\n1 2 3 4 5\n2 4\n", output: "9\n" }],
    conceptGuide: {
      coreConcepts: ["누적합 ps[i] = 1..i 합", "구간합 = ps[r]-ps[l-1]"],
      approachSteps: ["누적합 배열 구성", "질의마다 O(1) 계산"],
      pitfalls: ["인덱스 기준(0/1) 혼동", "long long 미사용으로 오버플로"],
      complexity: { time: "O(N+Q)", space: "O(N)" },
    },
  },
  {
    id: "meeting-room-greedy",
    title: "회의실 배정",
    difficulty: "Medium",
    tags: ["greedy", "sorting"],
    summary: "겹치지 않게 선택할 수 있는 최대 회의 수를 구합니다.",
    statement: "N개의 회의 (시작, 종료)가 주어집니다. 한 회의실에서 최대 몇 개를 진행할 수 있는지 출력하세요.",
    sampleInput: "3\n1 3\n2 5\n4 6",
    sampleOutput: "2",
    starterCode: `#include <bits/stdc++.h>\nusing namespace std;\nint main(){\n  int n; cin>>n;\n  vector<pair<int,int>> v(n);\n  for (auto &p: v) cin>>p.first>>p.second;\n  // TODO\n  return 0;\n}\n`,
    sampleTests: [{ input: "4\n1 4\n2 3\n3 5\n0 7\n", output: "2\n" }],
    conceptGuide: {
      coreConcepts: ["종료 시간이 빠른 회의를 우선 선택"],
      approachSteps: ["종료 시간 오름차순 정렬", "이전 종료 이후 시작하는 회의 선택"],
      pitfalls: ["시작 시간으로 정렬하면 최적 보장 안 됨"],
      complexity: { time: "O(N log N)", space: "O(1)~O(N)" },
    },
  },
  {
    id: "two-pointers-pair-count",
    title: "두 수 합 쌍 개수",
    difficulty: "Medium",
    tags: ["two-pointers", "sorting"],
    summary: "합이 X가 되는 서로 다른 쌍의 개수를 구하세요.",
    statement: "정수 배열과 목표값 X가 주어집니다. i<j 이고 a[i]+a[j]=X 인 쌍의 개수를 출력하세요.",
    sampleInput: "6\n1 2 3 4 5 6\n7",
    sampleOutput: "3",
    starterCode: `#include <bits/stdc++.h>\nusing namespace std;\nint main(){\n  int n,x; cin>>n;\n  vector<int>a(n);\n  for(int i=0;i<n;i++) cin>>a[i];\n  cin>>x;\n  // TODO\n  return 0;\n}\n`,
    sampleTests: [{ input: "5\n1 1 2 3 4\n5\n", output: "2\n" }],
    conceptGuide: {
      coreConcepts: ["정렬 + 양끝 포인터"],
      approachSteps: ["오름차순 정렬", "합 비교해 left/right 이동"],
      pitfalls: ["중복 값 처리 규칙 미정", "정렬 전 원본 인덱스 필요 여부 착각"],
      complexity: { time: "O(N log N)", space: "O(1)" },
    },
  },
  {
    id: "binary-search-lower-bound",
    title: "이진 탐색 하한",
    difficulty: "Easy",
    tags: ["binary-search"],
    summary: "정렬 배열에서 target 이상이 처음 나타나는 위치를 찾습니다.",
    statement: "정렬된 배열 A와 target이 주어집니다. A[i] >= target 인 최소 i(0-indexed)를 출력하고 없으면 -1을 출력하세요.",
    sampleInput: "5\n1 3 3 5 8\n4",
    sampleOutput: "3",
    starterCode: `#include <bits/stdc++.h>\nusing namespace std;\nint main(){\n  int n,t; cin>>n;\n  vector<int>a(n);\n  for(int i=0;i<n;i++) cin>>a[i];\n  cin>>t;\n  // TODO\n  return 0;\n}\n`,
    sampleTests: [{ input: "5\n1 2 4 4 9\n4\n", output: "2\n" }],
    conceptGuide: {
      coreConcepts: ["조건을 만족하는 첫 위치 탐색", "불변식 유지"],
      approachSteps: ["[lo, hi) 범위 정의", "mid 평가 후 범위 축소", "lo==n이면 -1"],
      pitfalls: ["무한 루프(중간값 계산/경계 갱신 실수)", "<= 와 < 조건 혼동"],
      complexity: { time: "O(log N)", space: "O(1)" },
    },
  },
  {
    id: "grid-bfs-shortest",
    title: "격자 최단 거리",
    difficulty: "Medium",
    tags: ["bfs", "graph", "shortest-path"],
    summary: "0/1 격자에서 시작점에서 도착점까지 최단 칸 수를 구합니다.",
    statement: "N*M 격자에서 0은 이동 가능, 1은 벽입니다. (0,0)에서 (N-1,M-1)까지 최단 거리를 출력하세요. 불가능하면 -1.",
    sampleInput: "3 3\n000\n010\n000",
    sampleOutput: "4",
    starterCode: `#include <bits/stdc++.h>\nusing namespace std;\nint main(){\n  int n,m; cin>>n>>m;\n  vector<string> g(n);\n  for(int i=0;i<n;i++) cin>>g[i];\n  // TODO\n  return 0;\n}\n`,
    sampleTests: [{ input: "2 2\n00\n00\n", output: "2\n" }],
    conceptGuide: {
      coreConcepts: ["무가중치 최단 경로는 BFS", "거리 배열로 레벨 관리"],
      approachSteps: ["큐에 시작점 삽입", "4방향 확장", "처음 방문 시 거리 갱신"],
      pitfalls: ["방문 체크 누락으로 중복 방문", "거리 초기값 설정 실수"],
      complexity: { time: "O(NM)", space: "O(NM)" },
    },
  },
  {
    id: "connected-components-dfs",
    title: "연결 요소 개수",
    difficulty: "Easy",
    tags: ["dfs", "graph"],
    summary: "무방향 그래프의 연결 요소 수를 출력합니다.",
    statement: "정점 N, 간선 M이 주어질 때 연결 요소 개수를 출력하세요.",
    sampleInput: "5 3\n1 2\n2 3\n4 5",
    sampleOutput: "2",
    starterCode: `#include <bits/stdc++.h>\nusing namespace std;\nint main(){\n  int n,m; cin>>n>>m;\n  vector<vector<int>> g(n+1);\n  for(int i=0;i<m;i++){int u,v;cin>>u>>v; g[u].push_back(v); g[v].push_back(u);}\n  // TODO\n  return 0;\n}\n`,
    sampleTests: [{ input: "4 0\n", output: "4\n" }],
    conceptGuide: {
      coreConcepts: ["미방문 정점에서 DFS/BFS 시작 시 컴포넌트 +1"],
      approachSteps: ["visited 배열 준비", "1..N 순회", "미방문이면 탐색 후 카운트 증가"],
      pitfalls: ["1-index/0-index 혼동", "재귀 깊이 제한 고려 누락"],
      complexity: { time: "O(N+M)", space: "O(N+M)" },
    },
  },
  {
    id: "tree-diameter-double-bfs",
    title: "트리 지름",
    difficulty: "Medium",
    tags: ["graph", "bfs", "tree"],
    summary: "가중치 없는 트리의 지름 길이를 구합니다.",
    statement: "N개 정점 트리가 주어집니다. 가장 먼 두 정점 간 거리(간선 수)를 출력하세요.",
    sampleInput: "5\n1 2\n2 3\n2 4\n4 5",
    sampleOutput: "3",
    starterCode: `#include <bits/stdc++.h>\nusing namespace std;\nint main(){\n  int n; cin>>n;\n  vector<vector<int>> g(n+1);\n  for(int i=0;i<n-1;i++){int u,v;cin>>u>>v; g[u].push_back(v); g[v].push_back(u);}\n  // TODO\n  return 0;\n}\n`,
    sampleTests: [{ input: "2\n1 2\n", output: "1\n" }],
    conceptGuide: {
      coreConcepts: ["임의 정점에서 가장 먼 정점 A 탐색", "A에서 가장 먼 정점까지 거리가 지름"],
      approachSteps: ["BFS(1) -> A", "BFS(A) -> 최대 거리"],
      pitfalls: ["방문 배열 재사용 시 초기화 누락"],
      complexity: { time: "O(N)", space: "O(N)" },
    },
  },
  {
    id: "coin-change-min",
    title: "동전 최소 개수",
    difficulty: "Medium",
    tags: ["dp"],
    summary: "목표 금액을 만드는 최소 동전 개수를 구합니다.",
    statement: "동전 종류 K개와 목표 금액 X가 주어집니다. 동전을 무한히 사용해 X를 만들 때 최소 개수를 출력하세요. 불가능하면 -1.",
    sampleInput: "3 15\n1 5 12",
    sampleOutput: "3",
    starterCode: `#include <bits/stdc++.h>\nusing namespace std;\nint main(){\n  int k,x; cin>>k>>x;\n  vector<int> c(k);\n  for(int i=0;i<k;i++) cin>>c[i];\n  // TODO\n  return 0;\n}\n`,
    sampleTests: [{ input: "2 3\n2 4\n", output: "-1\n" }],
    conceptGuide: {
      coreConcepts: ["1차원 DP: dp[금액] 최소 동전 수"],
      approachSteps: ["dp를 큰 값으로 초기화", "dp[0]=0", "각 금액/동전으로 점화식 갱신"],
      pitfalls: ["불가능 상태 처리 누락", "INF overflow"],
      complexity: { time: "O(KX)", space: "O(X)" },
    },
  },
  {
    id: "knapsack-01",
    title: "0/1 배낭",
    difficulty: "Medium",
    tags: ["dp"],
    summary: "무게 제한 내 최대 가치를 구하세요.",
    statement: "N개 물건(무게,가치)과 최대 무게 W가 주어집니다. 각 물건은 0번 또는 1번만 선택 가능합니다. 최대 가치를 출력하세요.",
    sampleInput: "3 7\n6 13\n4 8\n3 6",
    sampleOutput: "14",
    starterCode: `#include <bits/stdc++.h>\nusing namespace std;\nint main(){\n  int n,w; cin>>n>>w;\n  vector<int> wt(n), val(n);\n  for(int i=0;i<n;i++) cin>>wt[i]>>val[i];\n  // TODO\n  return 0;\n}\n`,
    sampleTests: [{ input: "1 5\n6 10\n", output: "0\n" }],
    conceptGuide: {
      coreConcepts: ["역순 순회 1차원 DP", "dp[c]=용량 c에서 최대 가치"],
      approachSteps: ["물건 하나씩 처리", "용량을 W..wt 역순 갱신"],
      pitfalls: ["정순 순회 시 같은 물건 중복 사용 버그"],
      complexity: { time: "O(NW)", space: "O(W)" },
    },
  },
  {
    id: "interval-scheduling-count",
    title: "겹치지 않는 구간 선택",
    difficulty: "Easy",
    tags: ["greedy", "sorting"],
    summary: "겹치지 않게 선택 가능한 구간 최대 개수.",
    statement: "N개 구간 [s,e]가 주어집니다. 서로 겹치지 않게 고를 수 있는 최대 개수를 출력하세요.",
    sampleInput: "4\n1 2\n2 3\n1 3\n3 4",
    sampleOutput: "3",
    starterCode: `#include <bits/stdc++.h>\nusing namespace std;\nint main(){\n  int n; cin>>n;\n  vector<pair<int,int>> seg(n);\n  for(auto &x:seg) cin>>x.first>>x.second;\n  // TODO\n  return 0;\n}\n`,
    sampleTests: [{ input: "2\n1 5\n2 4\n", output: "1\n" }],
    conceptGuide: {
      coreConcepts: ["종료 시각 기준 정렬 그리디"],
      approachSteps: ["e 오름차순 정렬", "현재 끝 이후 시작 구간만 선택"],
      pitfalls: ["끝점 포함/미포함 정의 불일치"],
      complexity: { time: "O(N log N)", space: "O(1)" },
    },
  },
  {
    id: "sliding-window-min-length",
    title: "부분합 최소 길이",
    difficulty: "Medium",
    tags: ["two-pointers", "sliding-window"],
    summary: "합이 S 이상인 연속 부분수열의 최소 길이.",
    statement: "양의 정수 배열과 S가 주어집니다. 합이 S 이상인 연속 부분수열의 최소 길이를 구하고 없으면 0을 출력하세요.",
    sampleInput: "6 7\n2 3 1 2 4 3",
    sampleOutput: "2",
    starterCode: `#include <bits/stdc++.h>\nusing namespace std;\nint main(){\n  int n,s; cin>>n>>s;\n  vector<int>a(n); for(int i=0;i<n;i++) cin>>a[i];\n  // TODO\n  return 0;\n}\n`,
    sampleTests: [{ input: "5 100\n1 2 3 4 5\n", output: "0\n" }],
    conceptGuide: {
      coreConcepts: ["합이 단조 증가/감소하는 투포인터"],
      approachSteps: ["right 확장으로 합 증가", "조건 만족 시 left 축소"],
      pitfalls: ["양수 배열 조건을 놓치면 알고리즘 불성립"],
      complexity: { time: "O(N)", space: "O(1)" },
    },
  },
  {
    id: "parametric-router-install",
    title: "공유기 설치",
    difficulty: "Medium",
    tags: ["binary-search", "greedy"],
    summary: "최소 거리의 최댓값을 파라메트릭 서치로 구합니다.",
    statement: "집 좌표 N개와 공유기 C개가 주어집니다. 공유기 사이 최소 거리의 최댓값을 출력하세요.",
    sampleInput: "5 3\n1\n2\n8\n4\n9",
    sampleOutput: "3",
    starterCode: `#include <bits/stdc++.h>\nusing namespace std;\nbool canPlace(const vector<int>& x, int c, int dist){\n  // TODO\n  return false;\n}\nint main(){\n  int n,c; cin>>n>>c;\n  vector<int>x(n); for(int i=0;i<n;i++) cin>>x[i];\n  // TODO\n  return 0;\n}\n`,
    sampleTests: [{ input: "3 2\n1\n10\n20\n", output: "19\n" }],
    conceptGuide: {
      coreConcepts: ["답을 이분탐색하는 파라메트릭 서치", "가능 여부 판정 함수"],
      approachSteps: ["좌표 정렬", "거리 mid로 설치 가능 여부 검사", "가능하면 거리 증가"],
      pitfalls: ["판정 함수에서 그리디 설치 기준 실수"],
      complexity: { time: "O(N log X)", space: "O(1)" },
    },
  },
  {
    id: "dijkstra-basic",
    title: "다익스트라 기본",
    difficulty: "Medium",
    tags: ["graph", "shortest-path", "dijkstra"],
    summary: "양의 가중치 그래프 단일 시작점 최단거리.",
    statement: "정점 N, 간선 M, 시작점 S가 주어집니다. S에서 각 정점까지 최단거리를 출력하세요(도달 불가: INF).",
    sampleInput: "5 6 1\n1 2 2\n1 3 5\n2 3 1\n2 4 2\n3 5 3\n4 5 1",
    sampleOutput: "0 2 3 4 5",
    starterCode: `#include <bits/stdc++.h>\nusing namespace std;\nint main(){\n  int n,m,s; cin>>n>>m>>s;\n  vector<vector<pair<int,int>>> g(n+1);\n  for(int i=0;i<m;i++){int u,v,w;cin>>u>>v>>w; g[u].push_back({v,w});}\n  // TODO\n  return 0;\n}\n`,
    sampleTests: [{ input: "2 0 1\n", output: "0 INF\n" }],
    conceptGuide: {
      coreConcepts: ["우선순위 큐 기반 다익스트라", "최단거리 확정 정점 확장"],
      approachSteps: ["dist 초기화", "(거리,정점) push", "pop 후 간선 완화"],
      pitfalls: ["오래된 pq 원소 skip 누락", "음수 간선에 사용하면 오답"],
      complexity: { time: "O((N+M) log N)", space: "O(N+M)" },
    },
  },
  {
    id: "floyd-warshall-mini",
    title: "플로이드 워셜 입문",
    difficulty: "Hard",
    tags: ["graph", "shortest-path", "dp"],
    summary: "모든 정점 쌍 최단거리를 구합니다.",
    statement: "정점 N(<=100), 간선 M이 주어집니다. 모든 i,j에 대해 최단거리 행렬을 출력하세요.",
    sampleInput: "3 3\n1 2 4\n2 3 1\n1 3 10",
    sampleOutput: "0 4 5\nINF 0 1\nINF INF 0",
    starterCode: `#include <bits/stdc++.h>\nusing namespace std;\nint main(){\n  int n,m; cin>>n>>m;\n  const long long INF = (long long)4e18;\n  vector<vector<long long>> d(n+1, vector<long long>(n+1, INF));\n  // TODO\n  return 0;\n}\n`,
    sampleTests: [{ input: "2 1\n1 2 3\n", output: "0 3\nINF 0\n" }],
    conceptGuide: {
      coreConcepts: ["중간 정점 k를 허용하며 점화식 확장", "d[i][j]=min(d[i][j], d[i][k]+d[k][j])"],
      approachSteps: ["초기 거리 설정", "k-i-j 3중 루프", "INF 출력 처리"],
      pitfalls: ["INF + INF 오버플로", "루프 순서 변경 시 의미 훼손"],
      complexity: { time: "O(N^3)", space: "O(N^2)" },
    },
  },
  {
    id: "topological-sort-order",
    title: "위상 정렬",
    difficulty: "Medium",
    tags: ["graph", "bfs", "topological-sort"],
    summary: "선행 관계를 만족하는 작업 순서를 출력합니다.",
    statement: "방향 비순환 그래프(DAG)가 주어질 때 가능한 위상 정렬 결과 중 하나를 출력하세요.",
    sampleInput: "4 3\n1 2\n1 3\n3 4",
    sampleOutput: "1 2 3 4",
    starterCode: `#include <bits/stdc++.h>\nusing namespace std;\nint main(){\n  int n,m; cin>>n>>m;\n  vector<vector<int>> g(n+1);\n  vector<int> indeg(n+1);\n  for(int i=0;i<m;i++){int u,v;cin>>u>>v; g[u].push_back(v); indeg[v]++;}\n  // TODO\n  return 0;\n}\n`,
    sampleTests: [{ input: "3 2\n1 2\n2 3\n", output: "1 2 3\n" }],
    conceptGuide: {
      coreConcepts: ["진입차수 0 정점부터 처리(Kahn)"],
      approachSteps: ["indegree 계산", "0차수 큐 삽입", "pop하며 인접 정점 차수 감소"],
      pitfalls: ["사이클 존재 시 길이가 N 미만", "우선순위 조건이 있으면 자료구조 변경 필요"],
      complexity: { time: "O(N+M)", space: "O(N+M)" },
    },
  },
  {
    id: "bfs-maze-with-break",
    title: "벽 한 번 부수기",
    difficulty: "Hard",
    tags: ["bfs", "state-graph", "shortest-path"],
    summary: "벽을 최대 한 번 부술 수 있을 때 최단 경로.",
    statement: "N*M 격자에서 0은 빈칸, 1은 벽입니다. 벽을 최대 한 번만 부술 수 있을 때 (0,0)에서 (N-1,M-1)까지 최단 거리를 구하세요.",
    sampleInput: "3 3\n010\n010\n000",
    sampleOutput: "5",
    starterCode: `#include <bits/stdc++.h>\nusing namespace std;\nint main(){\n  int n,m; cin>>n>>m;\n  vector<string> g(n);\n  for(int i=0;i<n;i++) cin>>g[i];\n  // TODO: dist[x][y][broken]\n  return 0;\n}\n`,
    sampleTests: [{ input: "1 1\n0\n", output: "0\n" }],
    conceptGuide: {
      coreConcepts: ["좌표 + 벽사용여부를 상태로 확장한 BFS"],
      approachSteps: ["dist[x][y][2] 준비", "빈칸 이동/벽 파괴 분기", "상태별 방문 관리"],
      pitfalls: ["좌표 방문만 체크하면 오답", "시작/도착 거리 정의 혼동"],
      complexity: { time: "O(NM)", space: "O(NM)" },
    },
  },
];
